### ISSUE TITLE
`make test` fails on Fedora24

### ISSUE THREAD

**Issue by ryanj** [sclorg/s2i-nodejs-container#106]
example `make test` output on F24:

```
Successfully built 30ae53632fda
2016-07-05 13:36:43,743 root         INFO     Running version 0.4.4, Docker ee81b72/1.10.3, API 1.22...
2016-07-05 13:36:43,743 root         INFO     Squashing image 'openshift/nodejs-010-centos7-candidate'...
2016-07-05 13:36:43,783 root         INFO     Old image has 13 layers
2016-07-05 13:36:43,783 root         INFO     Attempting to squash from layer sha256:40d63144482c811b217579cce280299b2c129ac60e904b2ef594131b51d06aa6...
2016-07-05 13:36:43,783 root         INFO     Checking if squashing is necessary...
2016-07-05 13:36:43,783 root         INFO     We have 12 layers to squash
2016-07-05 13:36:43,785 root         INFO     Saving image sha256:30ae53632fdada7c8050da88deca7e8552ce6d4e76b6db9ebb552a88c549f2af to /tmp/docker-squash-fMonNb/image.tar file...
2016-07-05 13:37:00,389 root         INFO     Image saved!
2016-07-05 13:37:00,413 root         INFO     Unpacking /tmp/docker-squash-fMonNb/image.tar tar file to /tmp/docker-squash-fMonNb/old directory
2016-07-05 13:37:00,749 root         INFO     Archive unpacked!
2016-07-05 13:37:00,750 root         INFO     New layer ID for squashed content will be: c3ba05ecea7c4d24682f663e8074e02ba916b481fa8b423eba88815bda581c63
2016-07-05 13:37:00,750 root         INFO     Starting squashing...
2016-07-05 13:37:00,750 root         INFO     Squashing layer 'sha256:30ae53632fdada7c8050da88deca7e8552ce6d4e76b6db9ebb552a88c549f2af'...
Traceback (most recent call last):
  File "/home/ryanj/.local/bin/docker-scripts", line 9, in <module>
    load_entry_point('docker-scripts==0.4.4', 'console_scripts', 'docker-scripts')()
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 96, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 88, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 31, in run_squash
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 497, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 337, in _squash_layers
  File "/usr/lib64/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib64/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: u'/tmp/docker-squash-fMonNb/old/sha256:30ae53632fdada7c8050da88deca7e8552ce6d4e76b6db9ebb552a88c549f2af/layer.tar'
hack/common.mk:25: recipe for target 'test' failed
```

**Comment by bparees** [comment]
what if you set SKIP_SQUASH=1?

@goldmann heads up.

**Comment by goldmann** [comment]
Please use latest docker-squash 1.0.0 RC.

**Comment by goldmann** [comment]
More info; this old version does not suport Docker 1.10 or later.

**Comment by ryanj** [comment]
Looks like the repo has moved and the pypi package names have changed?

I tried updating the script to use "docker-squash==1.0.0rc6", but I got the same error.

I'm using F24, which is currently shipping `Docker version 1.10.3, build ee81b72/1.10.3`

When I tried using `SKIP_SQUASH=1`, the build process asked me for my git commit signing key, which I declined to provide. I'm not sure why the script would need to make any git commits during the build.

**Comment by goldmann** [comment]
Besides installing docker-squash you need to adjust build scripts to actually use it. Without it it'll run docker-scripts. There was a rename some time ago, but from PyPi these are two separate projects.

**Comment by goldmann** [comment]
The binary and invocation is different. This needs to be fixed in the bud scripts. Please consult README for usage. Or run `docker-squash --help`.

**Comment by ryanj** [comment]
Thanks for the quick responses! 
PR submitted: #107

**Comment by goldmann** [comment]
That was fast! 👍

**Comment by goldmann** [comment]
@bparees @ryanj Small heads-up - I plan to release 1.0.0 very soon, please watch https://github.com/goldmann/docker-squash/releases
